const MENU = {
    intern: [
        "dashboard",
        "my-tasks",
        "submissions",
        "meetings",
        "chat",
        "profile",
    ],
    team_lead: ["Dashboard", "Intern Tasks", "Submissions Review", "Meetings", "Department Chat"],
    manager: ["dashboard", "analytics", "reports", "meetings", "chat"],
    admin: ["dashboard", "users", "settings"],
    cto: [
        "dashboard",
        "organization",
        "analytics",
        "reports",
        "chat",
        "settings",
    ],
    cfo: [
        "dashboard",
        "organization",
        "analytics",
        "reports",
        "chat",
        "settings",
    ],
    coo: [
        "dashboard",
        "organization",
        "analytics",
        "reports",
        "chat",
        "settings",
    ],
    ceo: [
        "dashboard",
        "technical",
        "operations",
        "finance",
        "meetings",
        "analytics",
        "reports",
        "announcements",
        "chat",
        "settings",
    ],
};

export { MENU };
